#!/bin/bash -e

## A simple wrapper to allow development/testing to occur in a container.

container="fioras"

here=$(dirname $(readlink -f $0))
cd $here

if ! docker image inspect $container 2>/dev/null 1>/dev/null ; then
	echo "Container not found, doing one time docker build"
	docker build -t $container -f tools/Dockerfile.dev-shell .
fi

set -x
cmd=$*
[ -z $cmd ] && cmd="/bin/bash"
exec docker run ${DOCKER_EXTRA} \
	-u $(id -u):$(id -g) \
	--rm -it \
	-v $here:$here \
	-w $here \
	$container $cmd
